defmodule SmsGatewayWeb.Router do
  use SmsGatewayWeb, :router

  import AshAdmin.Router

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_authenticated do
    plug :accepts, ["json"]
    plug SmsGatewayWeb.Plugs.ApiAuth
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug SmsGatewayWeb.Plugs.AdminAuth
  end

  scope "/api", SmsGatewayWeb do
    pipe_through :api

    # Public health check endpoint
    get "/health", HealthController, :show
  end

  scope "/api/v1", SmsGatewayWeb.Api.V1 do
    pipe_through :api_authenticated

    # SMS Messages API
    resources "/messages", MessageController, only: [:create, :index, :show]
  end

  # Admin interface (protected with Basic Auth) - AshAdmin autogenerated UI
  scope "/" do
    pipe_through :admin

    ash_admin("/admin")
  end
end
